const modalDisplay = [
    { id: 1, type: 'input', value: '', title: 'Label', placeholder: 'Field Label' },
    { id: 2, type: 'input', value: '', title: 'HTML Tag', placeholder: 'HTML Tag' },
    { id: 3, type: 'input', value: '', title: 'CSS Tag', placeholder: 'CSS Tag' },
    { id: 4, type: 'input', value: '', title: 'Attributes', placeholder: '' },
    { id: 5, type: 'input', value: '', title: 'Content', placeholder: '' },
    { id: 6, type: 'checkbox', title: 'Refresh On Change' },
    { id: 7, type: 'input', value: 'Sign above', title: 'Content', placeholder: '' },
    {
        id: 8,
        type: 'select',
        title: 'Label position',
        options: [
            { value: 'top', label: 'Top' },
            { value: 'left', label: 'Left' },
            { value: 'right', label: 'Right' },
            { value: 'bottom', label: 'Bottom' },
        ],
    },
    { id: 9, type: 'input', value: 'rgb(245,245,235)', title: 'Background Color', placeholder: 'Background Color' },
    { id: 10, type: 'input', value: 'black', title: 'Pen Color', placeholder: 'Pen Color' },
    { id: 11, type: 'input', value: '', title: 'Input Type', placeholder: 'Enter input Type' },
    { id: 12, type: 'checkbox', title: 'Hide Input Labels' },
    { id: 13, type: 'input', value: '', title: 'Inputs Label Position', placeholder: '' },
    {
        id: 14,
        type: 'select',
        title: 'Display in Timezone',
        options: [
            { value: 'ofviewer', label: 'of Viewer' },
            { value: 'ofsubmission', label: 'of Submission' },
            { value: 'oflocation', label: 'of Location' },
            { value: 'utc', label: 'UTC' },
        ],
    },
    { id: 15, type: 'checkbox', title: 'Use Locale Settings' },
    { id: 16, type: 'checkbox', title: 'Allow Manual Input' },
    { id: 17, type: 'input', value: '', title: 'Format', placeholder: '' },
    {
        id: 18,
        type: 'select',
        title: 'Options Label Position',
        options: [
            { value: 'top', label: 'Top' },
            { value: 'left', label: 'Left' },
            { value: 'right', label: 'Right' },
            { value: 'bottom', label: 'Bottom' },
        ],
    },
    {
        id: 19,
        type: 'select',
        title: 'Widget Type',
        options: [
            { value: 'choices', label: 'ChoicesJS' },
            { value: 'html5', label: 'HTML 5' },
        ],
    },
    { id: 20, type: 'input', value: '', title: 'Placeholder', placeholder: 'Placeholder' },
    { id: 21, type: 'input', value: '', title: 'Number of Rows', placeholder: '3' },
    { id: 22, type: 'input', value: '', title: 'Number of Columns', placeholder: '3' },
    { id: 23, type: 'checkbox', title: 'Clone Row Components' },
    {
        id: 24,
        type: 'select',
        title: 'Cell Alignment',
        options: [
            { value: 'left', label: 'Left' },
            { value: 'center', label: 'Center' },
            { value: 'right', label: 'Right' },
        ],
    },
    { id: 25, type: 'input', value: '', title: 'Custom CSS Class', placeholder: '' },
    { id: 26, type: 'input', value: '', title: 'Rows', placeholder: '' },
    { id: 27, type: 'input', value: '', title: 'Column Properties', placeholder: '' },
    { id: 28, type: 'checkbox', title: 'Auto adjust columns' },
    {
        id: 29,
        type: 'select',
        title: 'Action',
        options: [
            { value: 'submit', label: 'Submit' },
            { value: 'saveandstate', label: 'Save and state   ' },
            { value: 'event', label: 'Event' },
            { value: 'custom', label: 'Custom' },
            { value: 'reset', label: 'Reset' },
            { value: 'oauth', label: 'OAuth' },
            { value: 'posttourl', label: 'POST to URL' },
        ],
    },
    { id: 30, type: 'checkbox', title: 'Show Validations' },
    { id: 31, type: 'checkbox', title: 'Save On Enter' },
    { id: 32, type: 'input', value: '', title: 'Title', placeholder: 'Panel title' },
    {
        id: 33,
        type: 'select',
        title: 'Theme',
        options: [
            { value: 'primary', label: 'Primary' },
            { value: 'secondary', label: 'Secondary' },
            { value: 'info', label: 'Info' },
            { value: 'success', label: 'Success' },
            { value: 'danger', label: 'Danger' },
            { value: 'warning', label: 'Warning' },
        ],
    },
    {
        id: 34,
        type: 'select',
        title: 'Size',
        options: [
            { value: 'small', label: 'Small' },
            { value: 'medium', label: 'Medium' },
            { value: 'large', label: 'Large' },
        ],
    },
    { id: 35, type: 'checkbox', title: 'Block Button' },
    { id: 36, type: 'input', value: '', title: 'Left Icon', placeholder: 'Enter icon classes' },
    { id: 37, type: 'input', value: '', title: 'Right Icon', placeholder: 'Enter icon classes' },
    { id: 38, type: 'input', value: '', title: 'Shortcut', placeholder: 'Enter a keyboard shortcut' },
    { id: 39, type: 'input', value: '', title: 'Description', placeholder: '' },
    { id: 40, type: 'input', value: '', title: 'Tooltip', placeholder: '' },
    { id: 41, type: 'checkbox', title: 'Disable Adding / Removing Rows' },
    { id: 42, type: 'checkbox', title: 'Show key column before value' },
    { id: 43, type: 'input', value: '', title: 'Open First Row when Empty', placeholder: '' },
    { id: 44, type: 'input', value: '', title: 'Display EditGrid as Table', placeholder: '' },
    { id: 45, type: 'input', value: '', title: 'Conditional Add Button', placeholder: '' },
    { id: 46, type: 'checkbox', title: 'Allow Reorder' },
    { id: 47, type: 'input', value: '', title: 'Add Another Text', placeholder: 'Add Another' },
    {
        id: 48,
        type: 'input',
        value: '',
        title: 'Add Another Position',
        options: [
            { value: 'top', label: 'Top' },
            { value: 'bottom', label: 'Bottom' },
            { value: 'both', label: 'Both' },
        ],
    },
    { id: 49, type: 'checkbox', title: 'Equal column width' },
    { id: 50, type: 'checkbox', title: 'Enable Row Groups' },
    { id: 51, type: 'checkbox', title: 'Initialize Empty' },
    { id: 52, type: 'input', value: '', title: 'Label for Key column', placeholder: '' },
    { id: 53, type: 'input', value: '', title: 'Prefix', placeholder: 'Prefix' },
    { id: 54, type: 'input', value: '', title: 'Suffix', placeholder: 'Suffix' },
    { id: 55, type: 'input', value: '', title: 'Widget', placeholder: '' },
    { id: 56, type: 'input', value: '', title: 'Input Mask', placeholder: 'Input Mask' },
    { id: 57, type: 'input', value: '', title: 'Display Mask', placeholder: 'Display Mask' },
    {
        id: 58,
        type: 'select',
        title: 'Apply Mask On',
        options: [
            { value: 'change', label: 'Change' },
            { value: 'blur', label: 'Blur' },
        ],
    },
    {
        id: 59,
        type: 'select',
        title: 'Editor',
        options: [
            { value: 'ace', label: 'ACE' },
            { value: 'ckediter', label: 'CKEditer' },
            { value: 'quill', label: 'Puill' },
        ],
    },
    { id: 60, type: 'input', value: '', title: 'Tabs', placeholder: '' },
    { id: 61, type: 'checkbox', title: 'Auto Expand' },
    { id: 62, type: 'input', value: '', title: 'Input Mask Placeholder Char', placeholder: '' },
    { id: 63, type: 'checkbox', title: 'Allow Multiple Masks' },
    { id: 64, type: 'input', value: '', title: 'Tab Index', placeholder: '0' },
    { id: 65, type: 'input', value: '', title: 'Autocomplete', placeholder: 'on' },

    { id: 66, type: 'checkbox', title: 'Hidden' },
    { id: 67, type: 'checkbox', title: 'Hide Label' },
    { id: 68, type: 'checkbox', title: 'Show Word Counter' },
    { id: 69, type: 'checkbox', title: 'Show Character Counter' },
    { id: 70, type: 'checkbox', title: 'Hide Input' },
    { id: 71, type: 'checkbox', title: 'Initial Focus' },
    { id: 72, type: 'checkbox', title: 'Allow Spellcheck' },
    { id: 73, type: 'checkbox', title: 'Disabled' },
    { id: 74, type: 'checkbox', title: 'Modal Edit' },
];

export default modalDisplay;
